### ISSUE TITLE
After upgrading to the latest version or deleting this, Native Linux games are not showing up. 

### ISSUE THREAD

**Issue by nomadshiba** [nomadshiba/discord-steam-proton-rpc#4]
After upgrading to the latest version or deleting this, Native Linux games are not showing up.

**Comment by DeepDoge** [comment]
While I was first writing this, I didn't think other people would use it. 
So did some dumb decisions:

In the previous versions before `0.1.0`, I was moving Proton and Native Linux Games outside of the `/steamapps/common` and linking them back in. This hides them from Discord permanently, so there is no race condition.

Now, I re-wrote the whole thing and we don't need symbolic links anymore.

So to fix this issue:
- Goto `.../steamapps/common/` and delete every symbolic link folder there.
- Then goto `.../steamapps/__common_hidden__discord-steam-proton-rpc/` and move everything inside there to `.../steamapps/common/`

This should fix the issue.
